title: hdin0
email: hxd189@case.edu
description: "placeholder description"
url: https://hdin0.github.io
minimal_mistakes_skin: dark
author:
  name  : "Huay"
  bio   : "Woah, someone is reading this?"


theme: jekyll-theme-cayman